### ISSUE TITLE
Clicking on URL preview pictures don't lead to the URL

### ISSUE THREAD

**Issue by ndmckeown** [IsmaelMartinez/teams-for-linux#109]
**Describe the bug**
When you click on the generated preview image, it opens your browser to a blank page. Clicking the URL works as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send or receive a URL
2. When Teams generates a URL preview, click on it.
3. This will open a blank browser tab

**Expected behaviour**
Clicking on the URL Preview image should open the desired URL

**Screenshots**
![image](https://user-images.githubusercontent.com/27148947/56145586-7987f180-5f9c-11e9-8e29-7981fd1d00a4.png)

![image](https://user-images.githubusercontent.com/27148947/56145626-8d335800-5f9c-11e9-8310-4db00e0c000b.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Installation package: rpm
 - Version [e.g. 0.2.0]

**Additional context**
Dagnammit, Ismael!

**Comment by IsmaelMartinez** [comment]
Have you tried ctrl+click? Might be some sort of cookies/session stuff that is not pass throw.

I'm sure the link still works... Is just the "preview". Can you confirm??

**Comment by ndmckeown** [comment]
It's definitely just the preview that is affected.

**Comment by IsmaelMartinez** [comment]
Ok, this is a bit more difficult than expected. 

Basically, electron only gets the "about:blank" from the link. 

I am just pushing a wee change so that those link just don't do anything.

To fix this, it will need some js magic and/or maybe moving to the webview instead of the iframe... but webview is a not recommended path by electron (as google is re-implementing it).

So, I will leave it in here and see if someone can come up with a solution for it.

Sorry!

**Comment by orange-buffalo** [comment]
It looks like the same issue appears for actions in [cards](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference), like the ones posted by Jira, Jenkins or other connectors:

![image](https://user-images.githubusercontent.com/4532247/57206956-2211fa00-700d-11e9-8bde-a97e09a68307.png)

**Comment by IsmaelMartinez** [comment]
Hi @orange-buffalo ,

Does it work with Ctrl+Click?

Thanks

**Comment by orange-buffalo** [comment]
Hi @IsmaelMartinez , 
Sorry, I tried this before posting a comment, and a new blank popup window was opened. I just did not wait long enough - now I see that the URL is loaded successfully in this popup window..
The only problem is that it is not a browser window, but another Electron one. So obviously no cookies, extensions etc from my browser is accessible in this window. Is there any way to open the default browser instead of this popup, just like for any other link in a Teams message?

**Comment by IsmaelMartinez** [comment]
Not as far as I am aware. You can open an external window but that doesn't pass the cookies/credentials/etc... There might be a way, but I haven't found it

**Comment by HarlemSquirrel** [comment]
This seems to be the same issue as https://github.com/IsmaelMartinez/teams-for-linux/issues/107

**Comment by IsmaelMartinez** [comment]
Hi @nate-anderson and @orange-buffalo, this should be fixed now. 

It will be in version 0.4.0. I you want to check it use snap edge channel or send me an email.

@nate-anderson , you can just shout.

**Comment by orange-buffalo** [comment]
Hi @IsmaelMartinez, thanks for the new release! 
For actions in cards, they now open with a simple click (without ctrl), but it is still an electron window (with no URL bar to copy the link from). There was some work done in one of the PRs to actually open the underlying URL in system browser. Is there any chance for those changes to be included into the app?

**Comment by IsmaelMartinez** [comment]
Have you tried doing Ctrl+click? Otherwise raise a feature request. Might be ok to add a  "copy link" to the right click menu

**Comment by orange-buffalo** [comment]
Yes, it's the same with and without Ctrl. I've created #182 for this.
