### ISSUE TITLE
Can't set a custom background image

### ISSUE THREAD

**Issue by dejacazu** [IsmaelMartinez/teams-for-linux#1124]
I work for a company which has asked me to use a branded/professional background image when meeting clients

I attempted using the fakecam project, but it had limitations that didn't meet my needs. I also tried installing the Teams Windows app through Wine and Bottles, but the installation failed.

Windows, MacOS, iOS and Android users has support for custom backgrounds, it would be very appreciated to finally have this feature available on Linux if it is possible.

**Comment by jijojosephk** [comment]
please read this. https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md#custom-backgrounds. If you switched to `react`/`new` version (v2) of teams, this might not work.

**Comment by dejacazu** [comment]
Thank you @jijojosephk I'll try to set it up

**Comment by jijojosephk** [comment]
@dejacazu could you update? I'll close this for now.

**Comment by klm46** [comment]
This is still not possible and the linked file is not available anymore.

**Comment by IsmaelMartinez** [comment]
Hi @klm46 , thanks for reaching out. I would appreciate if you open a new ticket next time, or just put a message in the [gitter chat](https://gitter.im/teams-for-linux/community). Otherwise it can be a bit confusing; the dates can confused me.

You need to run a server. The info on how to set it up is in https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/config#custom-backgrounds . There is also an example of the server in https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/customBackground with instructions on how to run it and modify the images. 

If that doesn't work, do please open a new ticket and put as much information as possible, as it helps me get an idea of what is not working, and/or see if I can help.
