### ISSUE TITLE
Notification Sounds are Played Regardless of Setting.

### ISSUE THREAD

**Issue by kyle-goodwin** [IsmaelMartinez/teams-for-linux#1209]
**Describe the bug**

**To Reproduce**
1. Deselect both "Play Sound(s)" boxes in Setting
2. Get an notification.

**Expected behavior**
The application should make no noise when "Play sound(s)" are not selected.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/45823898/97ef8fa6-9b65-4385-87ac-f769aff3eb2c)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Installation package: deb
 - Version: 1.4.28

**Comment by jpurpleman** [comment]
I'm having the same issue on Linux Mint 23.1 on version 1.4.27

**Comment by jijojosephk** [comment]
The reason why you are facing this is, this app itself plays a sound when a notification comes. App can't access the settings shown above. With earlier version (`v1`) of teams, most people had a problem of sound not being played. So we added a feature to play a notification sound when there is a new notification. This is controlled by a config entry. But you can control from the menu itself.

Choose `Disable Notifications Sound`

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/9f74d2b9-9056-4cb5-8bee-8c4a16f593b5)

This setting is also useful with new (`v2`) teams when you hear the sound twice. It's again because the new teams successfully plays the sound but the app does not know if the sound played, so it plays again. So nowadays most people hear 2 `dings` for each notification. :smile: I hope this will work for you.

**Comment by andreaippo** [comment]
> The reason why you are facing this is, this app itself plays a sound when a notification comes. App can't access the settings shown above. With earlier version (`v1`) of teams, most people had a problem of sound not being played. So we added a feature to play a notification sound when there is a new notification. This is controlled by a config entry. But you can control from the menu itself.
> 
> Choose `Disable Notifications Sound`
> 
> ![image](https://private-user-images.githubusercontent.com/11662148/323825029-9f74d2b9-9056-4cb5-8bee-8c4a16f593b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTc3NDksIm5iZiI6MTcxMzg1NzQ0OSwicGF0aCI6Ii8xMTY2MjE0OC8zMjM4MjUwMjktOWY3NGQyYjktOTA1Ni00Y2I1LThiZWUtOGM0YTE2ZjU5M2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3MzA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWNlNGMzNzkzYTU2N2IyNTk0MjBlZTQ1ZTljOGQ1NmI2MGRhZTljMTMyNGJhZTlkMWEzMzEyOWJmMWVmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.InLPt4WlUZMLBQJCX1_OGnhj42FMoMF5KThpvIWe4lc)
> 
> This setting is also useful with new (`v2`) teams when you hear the sound twice. It's again because the new teams successfully plays the sound but the app does not know if the sound played, so it plays again. So nowadays most people hear 2 `dings` for each notification. 😄 I hope this will work for you.

Thanks so much for this, I was going crazy trying to understand why all of a sudden I was hearing twice the sound since v2.

I find Teams' ding very irritating, so 2x the daily dose won't be sustainable for me :laughing:

**Comment by kyle-goodwin** [comment]
This makes sense. I was pretty confused because these settings also stop the sound:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/45823898/da12b820-8a85-4871-ac65-8163e57645e8)
From what you're saying the lack of notifications at all stopped the app from playing it's own sound so that all makes sense.

For anyone else coming here looking to fix this. Pressing `Alt` brings up the menu shown and the location of the config file can be found in the config readme:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md

**Comment by IsmaelMartinez** [comment]
Pinning this as 2 dings must be annoying, and we can just always change the default value in the notification part, or try to be a bit more cleaver. I will have a think.
