### ISSUE TITLE
Question: Is there a way to force classic teams v1?

### ISSUE THREAD

**Issue by tppawelgrzesik** [IsmaelMartinez/teams-for-linux#1244]
I've had to reinstall my OS and thus also teams-for-linux.
Now after logging in to teams I get the following message:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/148882470/1695be99-078e-4d59-930b-a99c0e2ece65)

I cannot click cancel or abort, my only choice is "Switch now".
Once I do that, usually there would be a "Go back to classic teams" button somewhere at the top but now it's not available anymore.

Teams-for-linux with v2 loadaed is crashing silently sometimes.

**Is there any way I can stay on classic?**

Btw. until I click on "switch now" I see classic fully loaded in the background, with all chats and teams etc..

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/148882470/9ab4ba38-f09a-4c0b-855f-7328dc317c04)

**Comment by jakubbortlik** [comment]
> This means your organization is forcing you to switch to the new one. What's stopping you.

For me the reason not to switch is that the notification count in the system tray does not work in Version 2 (mentioned e.g., in [this comment](https://github.com/IsmaelMartinez/teams-for-linux/issues/1156#issuecomment-2022338012)). That's why I'm postponing the switch to the last possible moment and hope that by then, the notifications count will work correctly.

@tppawelgrzesik, you can get around the dialog with these steps:

1. Open the Developer Tools (Ctrl-Shift-I)
2. Select the elements picker: ![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/17056143/f3215563-115c-47fc-b15b-1bee11dff94f)
3. Click inside the grayed-out area. This should focus the Elements tab of the Developer Tools
4. Right-click on the highlighted element (or possibly a higher level element) that says `class="ngdialog ts-modal-dialog app-switcher-install-by-policy-dialog"` 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/17056143/ee1eef58-8f03-4bc3-bc6a-32afbe283a31)
5. In the context menu, select "Delete element"

Note that the next time you restart Teams for Linux, you'll see the dialog again.

**Comment by IsmaelMartinez** [comment]
Hi @jakubbortlik , the notification count should be working in v2. We did a fix a few versions ago so 1.4.37 should have that working.

The only part that ain't working yet is the incomming notification scripts and a few other activityHub features, but we will get to them

**Comment by jakubbortlik** [comment]
So I've managed to update to version 1.4.37, the notification count is working as expected and there's no reason to stay on version 1 for me.

Big thanks to everyone who's contributed to the `teams-for-linux` app and who's made Teams v2 available in it!

**Comment by IsmaelMartinez** [comment]
closing as we can't really force to keep on teams v1 as the company policy will force you to switch to v2. If you got any specific issue that is forcing you to stay with v1, let us know and we can see if there is already a fix and/or can prioritised.
