### ISSUE TITLE
Screen sharing problem

### ISSUE THREAD

**Issue by Anu-Ra-g** [IsmaelMartinez/teams-for-linux#1257]
I'm not able to share my screen during the video calls.

**Comment by jijojosephk** [comment]
@Anu-Ra-g  please use issue template. Otherwise use `discussions`. If you don't provide details, we can't really help.

**Comment by IsmaelMartinez** [comment]
Hi @Anu-Ra-g , please fill the template when opening issues. 

The use of the template is helpful for us to understand the issue and be able to help you. 

I put a copy in here:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version [e.g. 0.1.17]

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**
Add any other context about the problem here.

**Comment by IsmaelMartinez** [comment]
closing due missing information. Please re-open with more information and we will try to help. Thanks
