### ISSUE TITLE
Can't use Vietnamese in teams-for-linux

### ISSUE THREAD

**Issue by tneils218** [IsmaelMartinez/teams-for-linux#1264]
Can't use Vietnamese in teams-for-linux. Specifically with the new version of Teams

**Comment by tneils218** [comment]
@IsmaelMartinez  can you check this bug?

**Comment by IsmaelMartinez** [comment]
@tneils218 , can you check if you can use Vietnamese in the browser? Also, please fill the template when creating a bug/feature request with as much information as you can, as otherwise we can't really help much.

We don't do anything special with languages, but without more info we can't really help. Ta

**Comment by tneils218** [comment]
I can type Vietnamese in the browser. I was still using teams in the browser until I found your app 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/47965692/203b67a5-ff71-46f8-84ee-7555d1f7bf68)

**Comment by IsmaelMartinez** [comment]
Please fill the template and add as much info as you can.

**Comment by tneils218** [comment]
Im using Linux Fedora 40 and Teams V2 Idk ( New Teams) . In Vietnam we use an accented character to identify the meaning of a word. Exam: A Á . I said I can't use it because I can't let A turn into Á

**Comment by IsmaelMartinez** [comment]
I think it is some configuration in your system. check the close issues on configuring the locale for similar issues. I am sorry but I can't help more as you aren't providing enough information. Please edit the main issue and fill the template. It can also be related to the packaging system you are using, but you aren't providing that vital information. Having another guess, it could be a flatpak issue or snap, so try rpm or another package (we provide multiple options).

if is snap try this https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149 it might be related. Or this https://github.com/IsmaelMartinez/teams-for-linux/issues/1105#issuecomment-1947728319 .

I put a copy of the template in here so you can fill it. Please try all those options I mentioned and, if it doesn't work, fill the template with that information and modify your opening comment with it. Thanks

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version [e.g. 0.1.17]

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**
Add any other context about the problem here.

---

Without it, is as much use as me telling you. "it works for most people" what it wouldn't be as useful to you. Hope you understand you are making the resolution of your issue much more complicated to solve so we need your collaboration/help or the resolution will be nearly impossible.

**Comment by tneils218** [comment]
I will fill out the form after I finish my work. Can you try using your app with unikey vietnamese to test it?  You can use your app with vietnamese keyboard ibus-unikey or some tool can type vietnamese.  Some suggestions for you to type Vietnamese are as follows: A + S = Á, A + F = À, A + R = À, A + X = Ã, A + J = Ạ,

**Comment by IsmaelMartinez** [comment]
Can you check https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632446994 and see if that does anything to you?

**Comment by IsmaelMartinez** [comment]
I would recommend trying with another packaging system as snap many issues have been reported in snap that will not happen in other providers.

**Comment by IsmaelMartinez** [comment]
closing due inactivity
