### ISSUE TITLE
Clicking on a notification does nothing.

### ISSUE THREAD

**Issue by AchillesBoi** [IsmaelMartinez/teams-for-linux#1266]
**Describe the bug**
Clicking on an incoming message notification does nothing.

**To Reproduce**
1) Get a notification
2) Click on it
3) Stare at your monitor as it does nothing

**Expected behavior**
Clicking on a notification should take you directly to the message.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 - GNOME 42.9
 - Package: Flatpak version
 - Version: Latest Flatpak app

Additional notes:
This has been an issue with this app well before the Teams v2 update, but at least back then some notifications did put the app in focus (but still not the message). Now it doesn't even do anything anymore, so I had to switch to using it on Firefox or Chrome.

**Comment by IsmaelMartinez** [comment]
Hey, strange that stopped working but some people are using the `electron` notification instead of the `web` that I believe uses `libnotify`. Try using that config option and see if it works for you.

<img width="1271" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/29b6dbe9-a5e8-4483-8359-99c59de9647c">

There is some info on how to configure it at https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config . 

Another thing you can try is to run it with another packaging system. I have seen all weird issues with `flatpak` and `snap` configurations.

You can find the packages in the [releases section](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.37).

By my bet would be on the notification subsystem that is using.

**Comment by IsmaelMartinez** [comment]
Hi @AchillesBoi , I believe this is just a limitation on the app. We can't know the message or chat we have to open. 

We try to bring it back to focus, but in some desktop environments electron ain't that clever and thinks the app is on focus when it is actually minimised (or the other way around, I don't remember now), but that unfortunately is a electron limitation, that hopefully they will solve at some point.

As you managed to restore previous functionality, I will close this to keep things tidy. I think there is a ticket to improve the notifications somewhere (one of the old open tickets), but I will have a wee look later.
