### ISSUE TITLE
Running multiple instances of TFL - to handle different usernames?

### ISSUE THREAD

**Issue by jmergy** [IsmaelMartinez/teams-for-linux#1269]
**Is your feature request related to a problem? Please describe.**
Many of us have multiple Microsoft 365 logins and for a single login with multiple connections to organizations in Microsoft 365, TFL has been awesome. But I want to avoid multiple ins/outs on logins to hit these. 

**Describe the solution you'd like**
Does it make sense to isolate a couple of instances of TFL to have each connected to different M365 usernames/organizations?

**Describe alternatives you've considered**
Currently running TFL for my main username and I have multiple organizations under that. It's been awesome for the last year or so for that. I have dedicated a separate browser for the other instances with different usernames connected to different organizations. Just thinking I would try to run multiple TFL instances.

**Comment by IsmaelMartinez** [comment]
Check the discussions and/or close issues, as there are ways to have 2 sessions running in parallel (or as many as you need). 

You need to use the config options to have a different profile for each. I am not at my laptop so can't have a look but see if you find it. Ta

**Comment by IsmaelMartinez** [comment]
duplicate by https://github.com/IsmaelMartinez/teams-for-linux/issues/438

See in https://github.com/IsmaelMartinez/teams-for-linux/discussions/764#discussioncomment-5707658 (linked in the other one) for an example on how to use it. The appTitle part is not working if you are using teams-v2, and paths tend to be more reliable if you provide the full path, instead of a relative one.

**Comment by jmergy** [comment]
Thanks - confirmed the option suggested works well!
