### ISSUE TITLE
libgtk-3-0 dependency for Ubuntu 24.04

### ISSUE THREAD

**Issue by AlexLevkovich** [IsmaelMartinez/teams-for-linux#1396]
libgtk-3-0 dependency for Ubuntu 24.04 is invalid.
It cannot be installed. It must be libgtk-3-0t64.

**To Reproduce**
Try install deb on Ubuntu 24.04.

**Expected behavior**
Successful installation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.01
 - deb
 - the latest one

**Comment by IsmaelMartinez** [comment]
Thanks for reporting @AlexLevkovich , but I am not sure if we package the libgtk in the rpm. 

We use [electron-builder ](https://github.com/electron-userland/electron-builder)for the packaging, so it might be worth checking if they got a similar open issue. 

Can you provide some logs on what you are seeing? This way not only helps me but other users to confirm if the issue is the same for them. Thanks

**Comment by AlexLevkovich** [comment]
I will close this. It can't be installed by apt-get gui installer or Discover by dpkg does it without problem.

**Comment by AlexLevkovich** [comment]
oh I do not know how to close it. So please close it.

**Comment by IsmaelMartinez** [comment]
No worries and thanks for reporting
