### ISSUE TITLE
Recording never captures the screen share

### ISSUE THREAD

**Issue by azekeil** [IsmaelMartinez/teams-for-linux#1457]
**Describe the bug**
On Fedora 40 with Wayland. Recording a meeting works as expected, with the exception that only the users' webcams are shown, never the shared content. This occurs whether I start recording then share the screen, or share the screen then start recording. I always share a window as I have a 4k screen. Users on the call can see my screen share fine.

**To Reproduce**
As above

**Expected behavior**
Screen Recording captures screen share

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Installation package: rpm
 - Version: 1.11.1

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi @azekeil, thanks for reporting. 

Can you check if this also happens when using the browser version? It could be also related to wayland (some users do report issues with wayland and screen sharing).

Also, if you can provide some logs as the template suggest, it might help identify the issue.

**Comment by jijojosephk** [comment]
When you say `recording`, are you referring to the `recording` feature in the teams? Probably it can't record `4K`.

**Comment by IsmaelMartinez** [comment]
Without the logs is a bit more of a guess work, that can take much longer, but lets try to see where we get to. 

A few things you can try are:
* to do the screen share in the browser version and see what results you get. 
* using an older version of the app. In the [releases](https://github.com/IsmaelMartinez/teams-for-linux/releases) section you can see the changes. My initial suspicions tend to do with electron upgrades, that is the framework we use. Try:
* * [1.11.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.3) got the latest version of electron (33), it might be worth checking it in case is related to some changes in between. 
* * [1.10.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.10.3) is an older version (30) that was pretty stable

Otherwise, check in the logs and search the close issues for parts of those logs. 

If you identify anything in the logs that is concerning to be public, do please let me know. 

There is [a section on what we use for logs](https://github.com/IsmaelMartinez/teams-for-linux/blob/main/app/config/README.md#logconfig-option) that should hopefully explain how all that area works. Do let me know if you got any questions about it.

Thanks in advance and let me know how you get on.
