### ISSUE TITLE
Bad permissions after install or update for /opt/teams-for-linux/chrome-sandbox

### ISSUE THREAD

**Issue by javobalazs** [IsmaelMartinez/teams-for-linux#1462]
**Describe the bug**
ubuntu, /opt/teams-for-linux/chrome-sandbox is not 4755, have to set manually.

**To Reproduce**
Install or update teams-for-linux in ubuntu using the apt repository method.

**Expected behavior**
/opt/teams-for-linux/chrome-sandbox should have permissions 4755. It comes with 755 instead.

**Desktop (please complete the following information):**
 - OS: Linux xxxxx 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Installation package: apt
 - Version: 1.11.2 but it failed in previous versions, too.

**Comment by rborcherds** [comment]
I have this same issue if my machine does not shutdown correctly. I get the same error when I boot up the machine and try to start Teams.

The workaround for me that works is to run 

chmod 4755 /opt/teams-for-linux/chrome-sandbox

Then I can get back into Teams.

**Comment by javobalazs** [comment]
> I have this same issue if my machine does not shutdown correctly. 
I only have this after a fresh install or update
> chmod 4755 /opt/teams-for-linux/chrome-sandbox
This is what I do, too. As far as I know they can supply this command with the correct permissions right away in the setup package. I assume this is just a simple fix. Well, if I knew how to fix it I would do that.

**Comment by remicroset** [comment]
+1 here.
I've had the same problem since the last 3 updates at least.
`[11794:1101/091016.848221:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/teams-for-linux/chrome-sandbox is owned by root and has mode 4755.
Trappe pour point d'arrêt et de trace (core dumped)`
chmod fixes the problem too.

**Comment by IsmaelMartinez** [comment]
duplicated to https://github.com/IsmaelMartinez/teams-for-linux/issues/1426
