### ISSUE TITLE
Notifications only appear when in Chat section

### ISSUE THREAD

**Issue by jimpanse19** [IsmaelMartinez/teams-for-linux#15]
Hey, 

so i discovered the issue that i am getting notifications only when i am in a chat or in the chat section. 
When i am in the Teams section i do not get any visual Notifications for chats.

**Comment by IsmaelMartinez** [comment]
Check your configuration in teams (Microsoft part). By default, you don't get many notifications. You need to subscribe to channels and configure how do you want it to notify you.

Check the following links
https://support.office.com/en-us/article/manage-notifications-in-teams-1cc31834-5fe5-412b-8edb-43fecc78413d

https://www.unifysquare.com/blog/guide-to-microsoft-teams-notifications/

**Comment by jimpanse19** [comment]
Thanks for your fast reply.
I tried already every Notification function.

It is follwoing scenario:

When i am browsing in a Teams channel and switch to e.g. a browser in the foreground and then getting chat texts i don't get a visual notification.

It is working only if i stay in the Chat section.

Sorry for my bad explanation but maybe you understand what i am trying to say.

**Comment by IsmaelMartinez** [comment]
Could you provide more information with regards linux version, version of the app that you are using, what notification client are you using, is it business or personal account and any other information that might help understand more the issue?

**Comment by jimpanse19** [comment]
Linux Version: 
App Version: 0.1.9
Notification Client: build in notification ubuntu
Business Account

I tried it also in a VM but same issue.

**Comment by IsmaelMartinez** [comment]
I can see it now.

Basically, the browserwindow don't blur/focus when the parent one does (or not always). 

We are here relying in the title of the page changing in order to find the notifications. This is why it is called "notification hack". 

I think this could be related to this issue in electron https://github.com/electron/electron/issues/3472  and/or https://github.com/electron/electron/issues/5900

I have tried a few things but I can't fix it with the hack implementation. A work around is to minimise the app when loosing focus but that more annoying that anything else. 

Notice that if you use alt-tab to switch windows, it works fine. I will leave it open for the moment in case anyone wants to try to fix it, but I am afraid I will not be able to look into it much (at least for a good while).

Doing the notifications with a MutationObserver might be a better solution, but again, I have no time at the moment to implement this.

**Comment by jimpanse19** [comment]
Thanks for looking at it.
Still better then no notification at all.

**Comment by IsmaelMartinez** [comment]
Closing as no further work is to be carried out on this.
