### ISSUE TITLE
Camera drive discoverer cache usage is racey on macOS

### ISSUE THREAD

**Issue by Roberth-Mauricio** [IsmaelMartinez/teams-for-linux#1513]
The Camera drive discoverer on macOS has a race condition when accessing or updating its cache. This can cause,
Issues:
- Data Corruption: Multiple processes accessing the cache at the same time may result in incomplete or corrupted data.
- Random Failures: Cache access might fail under heavy use or when multiple threads are involved.
- Performance Problems: Poor handling of concurrent access could slow things down or cause deadlocks.
- Device Errors: Connected devices might be skipped, misidentified, or duplicated during discovery.
- This makes the component unreliable, especially in multi-threaded or high-load scenarios.

**Comment by IsmaelMartinez** [comment]
Hi @Roberth-Mauricio, 

Can you use the template and provide as much info as possible? I will close this issue until more information is provided. Otherwise I spend days going back and forward to gather some basic data (like version, logs, etc). I will reopen it once the info is provided, whoever be aware the app is called teams-for-linux, and the macOS support is a "side job" that is more complicated to support.
