### ISSUE TITLE
Calls not supported in this browser (flatpak)

### ISSUE THREAD

**Issue by ohthehugemanatee** [IsmaelMartinez/teams-for-linux#200]
**Describe the bug**
Removed the dpkg version and reinstalled from flatpak today. Now it won't let me make calls.

**To Reproduce**
1. Install from flatpak
2. (note that the video call button is greyed out) Try to initiate a call

**Screenshots**
https://germany.vertesi.com/index.php/s/5kaGQRWkeQBcjx3

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 with i3wm
 - Installation package: flatpak
 - Version 0.4.0

**Comment by IsmaelMartinez** [comment]
You will need to wait until 0.5.0. use another package type until then.

**Comment by IsmaelMartinez** [comment]
As a reference, this should be duplicated by #194. 

Otherwise, there is a wee annoyance if the app starts on a 1-2-1 chat. The icon appears grey out. If you go to a group chat and back to the 1-2-1, then you can make the call, etc.

Closing as is either duplicated or a known issue. Let me know how you get on.
