### ISSUE TITLE
No option to select audio device for meetings

### ISSUE THREAD

**Issue by tulanian** [IsmaelMartinez/teams-for-linux#21]
When I join a meeting, under Devices I see options for selecting the Microphone and Camera devices but not Audio, so the audio only comes out of the main speakers of my laptop instead of the headset. In an actual browser I'm given options for all three. I've tried it on v0.1.8 and v0.1.9 and the behaviour is the same. Running it on Fedora 29.

**Comment by IsmaelMartinez** [comment]
Hi @tulanian, I can see that in Microsoft Edge (windows 10) the Speaker option is also not available so is a Microsoft Edge issue. 

Elaborating: 
We are using Edge as the user agent but doing quite a hack (moving from Chrome to Edge on start) so that we have the video and mentions working. 

They accept issues/ideas in their public channel (one of the top 3 is the linux client... that hopefully one day will remove the need of this project):
https://microsoftteams.uservoice.com/forums/555103-public

Workaround:
I don't use fedora myself but maybe you can bypass this by setting the default audio (assume using the pavucontrol but not sure (https://fedoramagazine.org/precise-audio-control-with-fedora/)). In any case, is really annoying needing to change the audio setting every single time you get into a meeting. (another one for Microsoft official channel) 

Another option, but less elegant from my point of view, is to use version 0.1.7. 
You will not be able to use video calls as it uses the Chrome user agent.  
There are a few other things that don't work on that version like drag and drop, it doesn't persist the session and it doesn't focus you to the teams windows when you click on a notification.

Closing as it is the current Microsoft Edge behavior so Microsoft should be dealing with it (or allowing video to the chrome user agent!!)

**Comment by julian-alarcon** [comment]
Maybe using a cleaner option to allow Audio/video calls can solve this issue:

https://techcommunity.microsoft.com/t5/Microsoft-Teams/TEAMS-and-LINUX-The-Future-is-Now/m-p/355250/highlight/true#M26671

> Basically it sets a value in the settings that enables this function: 
angular.element(document).injector().get('callingSupportService').oneOnOneCallingEnabled = true 
angular.element(document).injector().get('settingsService').appConfig.enableCallingChromeOneOnOne = true

**Comment by IsmaelMartinez** [comment]
I am not sure when I will be able to have a look at this, but sounds like a better workaround than switching user agent. Reopening and adding "help wanted" to see if someone else can try it. Thanks!!

**Comment by IsmaelMartinez** [comment]
Ok, this is now been release as part of the release 0.1.15. Thanks again @julian-alarcon for pointing out the alternative solution to the userAgent hack!

**Comment by tulanian** [comment]
This is great, thanks so much!

---

<https://www.vizify.com/es/501a727aba8a2200020003b3>
http://www.gunternation.com
http://www.slowfooddublin.com

"I think we delight to praise what we enjoy because the praise not merely
expresses but completes the enjoyment; it is its appointed consummation."
Reflections on the Psalms, C.S. Lewis

**Comment by george-norton** [comment]
Video calls aren't working for me in 0.1.15, it looks like one of the options from the previous comment is missing. If I add:
`angular.element(document).injector().get('callingSupportService').oneOnOneCallingEnabled = true;`
Then it works work.
