### ISSUE TITLE
Enable right clicking on URLs

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#230]
**Is your feature request related to a problem? Please describe.**
When someone sends me an URL i like to right click on it and choose "copy url" so i can decide myself in which browser window to open. Unfortunately right clicking is disabled in teams for linux

**Describe the solution you'd like**
Enable it!

**Describe alternatives you've considered**
Doesn't apply here.

**Additional context**
As right clicking is allowed when opening teams in the web browser it seems to be an issue with teams for linux itself

**Comment by IsmaelMartinez** [comment]
Hi @mschirmacher, Thanks for the suggestion.

Tlectron doesn't include a full browser so things like this have to be implemented a side of it. 

We have currently a right click menu implementation for `textarea, input, [contenteditable="true"]` but there should not be much work to expand it to support other sections. Code in here:

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/rightClickMenuWithSpellcheck.js

Maybe it just need to only show a fewer options. Feel free to give it a go and shout for help if you need it. I put the `help wanted` and `good first issue` to see if someone can pick it up, otherwise it just needs to wait until I got time.

**Comment by mschirmacher** [comment]
Thanks! I will look on it, when i find some time - unfortunately i'm not even a javascript developer ;-)

**Comment by IsmaelMartinez** [comment]
It's never too late... Shout if you got any questions, is probably a good
example of front end vanilla JavaScript. Even if the file is a but of a
mess...

**Comment by pault929** [comment]
I'm so new to this, where and what file is this in?

**Comment by IsmaelMartinez** [comment]
> Hi @mschirmacher, Thanks for the suggestion.
> 
> Tlectron doesn't include a full browser so things like this have to be implemented a side of it.
> 
> We have currently a right click menu implementation for `textarea, input, [contenteditable="true"]` but there should not be much work to expand it to support other sections. Code in here:
> 
> https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/rightClickMenuWithSpellcheck.js
> 
> Maybe it just need to only show a fewer options. Feel free to give it a go and shout for help if you need it. I put the `help wanted` and `good first issue` to see if someone can pick it up, otherwise it just needs to wait until I got time.

Check that comment, and do let me know if you need any hints.

**Comment by IsmaelMartinez** [comment]
if anyone is interested in this one, shout! otherwise I will pick it up, and close, soon.

**Comment by lkreimann** [comment]
This is done, right?!

**Comment by IsmaelMartinez** [comment]
Done in snap edge. Soon in master branch

**Comment by lkreimann** [comment]
Looking forward to this feature! :nerd_face:

**Comment by IsmaelMartinez** [comment]
I need to get sometime to release to master. Apologies but I have been sick for over a week now so will need to wait a wee bit longer. Sorry!
