### ISSUE TITLE
Click behavior on icon systray

### ISSUE THREAD

**Issue by smonat** [IsmaelMartinez/teams-for-linux#244]
Description of the problem :
When a notification has appeared (number with a red ball) on the systray icon we would like to :
1. Click left to open the window
2. Click right to have the menu Open / Refresh / Hide / Debug / Quit

For now the right or left click are doing the same action ie open the menu.

Do you think you can change that behavior easily ?

**Comment by IsmaelMartinez** [comment]
Hi @smonat , I think depends on the tray manager but I might be wrong as I am also seen the same issue. 

I mark it as bug, help wanted and see if someone can have a look at it.

Thanks for reporting!

**Comment by byteSamurai** [comment]
Before I head into it: What desktops are you using @IsmaelMartinez  & @smonat

**Comment by IsmaelMartinez** [comment]
Hi @byteSamurai . I got KDE /plasma. I am off my computer for a few days son can't really check specifically task manager and so on... But it use to work. Does it work for you?

**Comment by smonat** [comment]
Hi @byteSamurai, I got Xubuntu so XFCE for me ...

**Comment by byteSamurai** [comment]
And I am using Gnome with an extension. Okay, so I will test these three.

**Comment by ocafebabe** [comment]
Same behavior as OP on Mint / Cinnamon. Would be neat to get the window open on left click!

**Comment by byteSamurai** [comment]
I was playing around with it, but I think we cant fix it. Citing from the docs:

>If you want to keep exact same behaviors on all platforms, you should not rely on the click event and always attach a context menu to the tray icon.

As far I have read this is mostly due to the limitations of libappindicator.

\# of evil imho is here:
https://github.com/electron/electron/issues/6773

In short terms: We could recompile electron without libindicator support [as this worked for an developer 2016](https://github.com/electron/electron/issues/6773#issuecomment-248759451). 

Saying this, I am not sure if its worth spending so much energy here. We are talking about an inconvenience, not a real issue. 

>Do you think you can change that behavior easily ?

Unfortunately not, sry

**Comment by IsmaelMartinez** [comment]
Hopefully, a new version of electron fixes this. Thanks a lot for having a look at it @byteSamurai
