### ISSUE TITLE
Closing Teams window doesn't close processes

### ISSUE THREAD

**Issue by homebrew79** [IsmaelMartinez/teams-for-linux#32]
I've noticed that when I close the teams window, it leaves 5 teams processes running. Then, when I launch a new instance, it starts up another 5 processes. And so on. I would expect that when I close the window it shuts down all of the processes. Or it would at least give me the option to keep it running in the background, like the native windows client.

Fedora 29 x86_64.
Version 0.1.10

**Comment by IsmaelMartinez** [comment]
Hi, 

If you close using the cross in hides the window but doesn't close it. Do you experience the same issue if you click on the tray bar icon and select quit?

Version 0.1.10 is a pre-release that will probably never get released. Try using version 0.1.9 and see if that still happening.

Thanks,

**Comment by IsmaelMartinez** [comment]
yeah, go for it. We are using the config area to allow parameters and other configuration options. Check the webDebug as an example.

That change should then ignore the "shouldQuit" boolean in the index.js file in the menus folder (around line 40). 

If you can try the current code 0.1.11 and see if you can still not get issue #31 working that will be great. I have change all that area since then and we are not using "open" anymore, so that might fix your issue also.

I am trying to add #28 before releasing 0.1.11 and waiting for #27 probably. Might try to get it done at some point this week/weekend but I am not sure how much time I will have.

**Comment by IsmaelMartinez** [comment]
Just added the option to close the app when clicking the cross. Start teams with the following

`teams --closeAppOnCross` 

This should be available in the next release (0.1.11). You can check yarg documentation for extra options on how to start with those options (like having a properties file)

**Comment by IsmaelMartinez** [comment]
Hi @homebrew79 ,

Version 0.1.11 is ready (pre-release) and should have cover this issue. Can you test it and reopen if is not the case?

Thanks,
Ismael

**Comment by homebrew79** [comment]
Works great! Thanks for doing that.

**Comment by alumni** [comment]
Instead of QuitOnClose you should provide and option for MinimizeOnClose. The trend nowadays is to remove the system tray and quit on close by default (not just on Gnome, that's how most Linux apps behave). While I don't like it either, Gnome for example has no tray and it is no longer possible to add one using extensions. So Gnome users end up with the app running in the background with no possibility to reopen it when they expect it to be closed.

**Comment by IsmaelMartinez** [comment]
I see the point but I tend to be cautious on changing defaults (more the ones that I have inherited).

If it was a new implementation I will have probably agreed with that option should be the default. 

It's also true that the current default is closer to other platforms behaviour (so keeps cross platform usability similar)... 

Resuming, it is one of those were is impossible to please everyone.

The best compromise I found is to add an option. It's a bit of a pain that is an argument but, from version 0.1.18 (or 0.2.0) you should be able to have a config file with this sort of values. See #80.

That removes the need of passing the arguments (or remembering them) and I hope closes a bit the gap and pleases more people.

Hope helps and I hope you understand where I am coming from when I don't change that default.
