### ISSUE TITLE
Logs me out of everything in chrome, if I open a link from chat, without having a browser open first.

### ISSUE THREAD

**Issue by g4borg** [IsmaelMartinez/teams-for-linux#321]
**Describe the bug**
I have a weird issue when I click on links in chat, and it took a while until I realized why chrome keeps asking me to re-authenticate every now and then; and this only happens from teams for me.
Without a running chrome instance, the next chrome that gets opened, if i click on a link in chat, is completely resetting all logins, and I have to re-authenticate with every service I use browser wide.

**To Reproduce**
1. Have Chrome installed (I have a syncing google account set up)
2. Have it not running
3. Click on a link in a chat, which opens chrome
4. Check if logins (facebook, etc.) still work or require re-authentication
4a. another hint is, that the current profile in Chrome is on "sync paused" and stays there. once you have that browser open, closing it and reopening it is already too late. the profile is somehow reset.

**Expected behavior**
Should not do this. 
Clicking on links in the official microsoft teams works as expected (so do other apps), so it must be the way the browser is called.
If the browser is already running, behaviour is fine (new tab is opened)

**Desktop (please complete the following information):**
 - OS: Linux, KDE Neon (based on Ubuntu 18.04 bionic)
 - Installation package deb
 - Version: tried 0.6.6, 1.0.1

**Additional context**
Might be related to chrome, or electron, or kde, of course.
Is definitely low priority, as there is a workaround (simply have a browser open before clicking links)
And it is a minor hassle (one can simply log back in)
However, it would interest me, how this can happen; so mainly I would be happy to investigate how links are opened differently here.
I used the official teams as comparison, which does not have this issue (however is unusable for me due to it's excessive CPU usage)
I will also check other electron apps.

Yes I know this is a somewhat weird issue, but maybe someone else is wondering why he gets random re-authentications. It probably happens since forever.

**Comment by IsmaelMartinez** [comment]
Hi @g4borg, thanks for reporting.

The app uses the shell.openExternal:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L131

More info in here:
https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options

Not sure if that can be of any help. When opening an external URL it will not keep the authentication from the teams client itself. This is because of the packaged version of chrome that comes with the app is not the same as your chrome browser. But, in theory, what you are saying should just work.

Another workaround is opening the links with the CTRL key pressed.That will open them in an internal window (but without tabs etc). Hope helps

**Comment by IsmaelMartinez** [comment]
There ha sheen no new comments for a while so closing. Please ping if you want/need it reopen. Thanks
