### ISSUE TITLE
Thanks for your software

### ISSUE THREAD

**Issue by Strauman** [IsmaelMartinez/teams-for-linux#324]
As Microsoft now has made an official Teams app available for Linux, I wanted to take the time to thank you for your unofficial version. My guess is that it is a big factor as to why they actually ended up doing it (and also why people asked them to). 

So thanks :slightly_smiling_face:

**Comment by AkselMeola** [comment]
Thank you so much. Your app really helped to make the Teams experience bearable.

**Comment by teseo** [comment]
I'm still using this app because the official one is just draining my resources. Good job @IsmaelMartinez !

**Comment by IsmaelMartinez** [comment]
I will close this issue but not without thanking you all for your kind words. I honestly, can’t believe this is still been useful. I am also using it as the ms one eats all my computer memory... and the laptop I got it’s a small beast. Hopefully they sort it out soon. Thanks again

**Comment by zeitounator** [comment]
I am (and the 100+ fastly growing community of linux users in the 250k+ Microsoft centric company are) still using it because it contains the fixes I PRed myself to support SAML login with a company signed cert... which was still not supported/working correctly on the official application last time I tried (and I am a little fed-up to test and report every few days). Moreover, if everyone agrees the memory footprint of this dissident app is lower, I'll stay out of the line for now :)

**Comment by IsmaelMartinez** [comment]
Thanks again for that fix. You have contributed to enable other users in the same situation been able to, basically work and communicate with each other. Thanks again
