### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by frealgagu** [IsmaelMartinez/teams-for-linux#332]
**Describe the bug**
Error compiling package with yarn

**Desktop (please complete the following information):**
 - Linux Arch
 - Building an arch package
 - Version 1.0.0, 1.0.1

**Additional context**

The following error is happening trying to build a package with yarn:

/build/.cache/node-gyp/13.11.0/include/node/node.h:618:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  618 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/build/.cache/node-gyp/13.11.0/include/node/node.h:652:3: note: in expansion of macro ‘NODE_MODULE_X’
  652 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/main.cc:299:1: note: in expansion of macro ‘NODE_MODULE’
  299 | NODE_MODULE(spellchecker, Init)
      | ^~~~~~~~~~~
make: *** [spellchecker.target.mk:120: Release/obj.target/spellchecker/src/main.o] Error 1
make: Leaving directory '/build/teams-for-linux/src/teams-for-linux-1.0.1/node_modules/spellchecker/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.5.10-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /build/teams-for-linux/src/teams-for-linux-1.0.1/node_modules/spellchecker
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by IsmaelMartinez** [comment]
I think is your version of node. 

use  12.13.0 or similar and it should work.

for arch related issues better ask in https://aur.archlinux.org/packages/teams-for-linux

hope helps!

**Comment by micwoj92** [comment]
One year later and the build still fails on nodejs-lts-fermium (14.16.0) and nodejs (16) when trying to build 1.0.6 and 1.0.7. This isn't that much of a problem now because the older nodejs lts versions aren't going anywhere soon (at least on Arch) but it still would be nice to be able to build using latest nodejs version. 

> for arch related issues better ask in https://aur.archlinux.org/packages/teams-for-linux

Well, that person who opened issue is AUR package maintainer for teams-for-linux so if he doesn't know it then I think you are the right one to ask for help with this. I could quickly setup vm with Debian for example and test build with nodejs versions higher than 13 there if that's necessary but I think it will give same error.

**Comment by IsmaelMartinez** [comment]
I suspect that will need an upgrade of the electron version. Unfortunately that the breaks a lot of stuff.

I welcome new PRs and I am happy to help but, this days, my company laptop is a Mac so makes things pretty complicated.

Since MS has an official version, probably best ask if they are going to support AUR.

**Comment by micwoj92** [comment]
Official Teams package and insiders edition are in AUR under names teams and teams-insiders if that's what you meant.  Nodejs version 12 has maintenance until 2022-04-30 so there's plenty of time till then. Thank you for quick response.
