### ISSUE TITLE
Usage question: Problem with joining meetings from the calendar (no enhancement request or bug report ;-))

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#379]
I do encounter a problem with joining meetings from the calendar within the teams client. Does anyone else here encounter such problems? In those cases the client jumps directly to the "Teams" tab. 
Opening the appointment in the browser gives me a chance to submit a chat message and from the chat in the client I can then join the meeting.

**Comment by IsmaelMartinez** [comment]
Hi,

Can you confirm the following details?

----

Bug description

I can not join meetings using the calendar within the teams client

To Reproduce Steps:

*Go to* The teams calendar
*Click on* a meeting that you with to join
*Then* client switches to the team channel not the meeting request itself.

Expected behavior:

The client switches to the meeting. 

-- a gif or set of screenshots could help -- 

Desktop (please complete the following information):

OS: Linux 5.3.18-lp152.36-default x86_64 GNU/Linux, which is Opensuse Leap 15.2
Installation package rpm
Version 1.0.5
Additional context:

-- further information about the bug/issue -- 

----
If that is the case, please change your initial report to it. 

Apologies but it makes it much more easier to know the problem when information is provided using the templates. 

I will reopen but suggest the following tests:

* Create a meeting that happens ina channel
* Create a meeting that doesn't happen ina channel

Confirm if you got the same behaviour in both. My suspicion is that, somehow, that might be the issue.

I have no linux machine available anymore so I can't do any testing or development in this client. Happy to help and/or provide feedback but my hands are tied now.

**Comment by elhennig** [comment]
Actually I am still not 100% sure, it is a bug and as it only occurs sporadically it is quite difficult to reproduce. As I wrote, my goal is, to find out, if this is an error/bug within the client or not.
Do you have any hint or tip what I can do to debug the session in order to get more information, why some meetings do not connect while others work fine?

**Comment by IsmaelMartinez** [comment]
Did you run my tests?

**Comment by elhennig** [comment]
Usually I do not use channels in my Teams for meetings. I use Outlook/Exchange to schedule meetings. Anyway I will try...

**Comment by elhennig** [comment]
Both of my meetings one within a channel, one scheduled from Outlook. With both the join dialogue pops up and I can then join the meeting, the client does not switch to the "Teams" tab.

**Comment by IsmaelMartinez** [comment]
then is probably them not ticking the "teams meeting" in outlook. Normally then you don't even get the "Join" button in the meetings.
![image](https://user-images.githubusercontent.com/430992/91030642-63119180-e5f7-11ea-8eaf-d2e6d2310f2d.png)

**Comment by elhennig** [comment]
The join button is there, and the meeting description shows the connect link. Clicking on it returns immediately without actually joining. Sometimes I can the submit a chat message to the meeting chat and then login from the chat tab. My impression is that our IT guys messed something up, but their usual answer is, that this is caused by running Linux, so they don't have to look for the real reason. To avoid this, I wanted to check with you before. For me it is difficult to distinguish between the web and the client functionality. Thanks a lot already for your time!

**Comment by IsmaelMartinez** [comment]
I think it will be better to go to the https://microsoftteams.uservoice.com/ and explain the issue but just referring this client as the web browser (as it works the same way as the browser version on their books). There is a bit of oddity on those calendars stuff
