### ISSUE TITLE
Use native file dialog on Qt-based desktop environments

### ISSUE THREAD

**Issue by mara004** [IsmaelMartinez/teams-for-linux#404]
Currently, when downloading or uploading a file in teams-for-linux, the gtk file selector dialog turns up, which looks rather out of place in KDE Plasma (or LXQt). It would appear more native if KDialog / xdg-dektop-portal-kde could be used instead.
However, it's electron's fault; see [this thread](https://github.com/electron/electron/issues/2911).
Perhaps https://github.com/codebytere/native-kde-file-open could be used as a workaround until the upstream issue is fully resolved?

**Comment by IsmaelMartinez** [comment]
Hi,

Feel free to create a PR with the needed changes. I suspect we will not be able to increase the version of electron (stuck in 4) as it otherwise breaks a lot of other functionality. 

The native kde file hack could work but you will need to detect if that file open is available (so that you aren't running another desktop. 

Probably better to solve that problem in https://github.com/sindresorhus/electron-dl that is the library we use for the download dialog.

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Do ping me to reopen if you got a PR. Thanks
