### ISSUE TITLE
Joining Meetings outside the own organization fails

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#407]
Hi, I have a strange behavior here: I tried to join a meeting organized outside my oy organization and I was admitted to the waiting room. Once the organizer let me in, the call was interrupted. Teams printed the error message, that something went wrong with joining the call.
When I switched to the official MS client this did not happen. Any idea what could be the cause for this?

Version  teams-for-linux     1.0.5 
snap           2.48.2-lp152.1.1
series         16
opensuse-leap  15.2
kernel         5.3.18-lp152.60-default

**Comment by IsmaelMartinez** [comment]
Sorry, I have no idea. Did you see any logs and/or error message in the syslogs? (or whatever log system opensuse uses?)

**Comment by elhennig** [comment]
Is there an option to gain more debug infos?

**Comment by IsmaelMartinez** [comment]
Yes, Start the app via a terminal. Make sure your current teams-for-linux is fully close (no icon in the tray) and run
```teams-for-linux --webDebug```

Then logs do appear in 2 areas. The electron (or backend) errors/messages in the terminal and the browser in the devtools. 

If you have done any UI development you should be familiar with the devtools, otherwise google for chrome developer tools, but you should be interested in the console part. 

ms does print a lot of "stuff" in the console, so don't be alarm on the amount of red you will see. Hope helps!

**Comment by elhennig** [comment]
I just noticed that screensharing does not work anymore, too.

**Comment by IsmaelMartinez** [comment]
that is already reported in https://github.com/IsmaelMartinez/teams-for-linux/issues/406 . thanks for pinging in here.

**Comment by elhennig** [comment]
Thanks for the hint regarding #406. Missed that earlier...

**Comment by elhennig** [comment]
Today it worked joining an external hosted teams meeting with 1.0.6 from snap

**Comment by IsmaelMartinez** [comment]
well, that is strange but I suspect it was an xdg-open issue. Maybe an update in your linux fixed it. Closing then. Glad is sorted and thanks for reporting back. Ta
