### ISSUE TITLE
YATY: Yet Another Thank You

### ISSUE THREAD

**Issue by zeitounator** [IsmaelMartinez/teams-for-linux#410]
**Is your feature request related to a problem? Please describe.**
As a user I would like to point out the TREMENDOUS work done by @IsmaelMartinez on this project. I would like to thank him on behalf of hundreds of developers using linux as a dev environment at La Poste (French post office) who where in the dark and have been able to see the light during the last months. I just wish Microsoft had a different strategy and had been able to overtake this magnificent piece or software to build upon it rather than re-inventing the wheel.

Meanwhile (we knew this moment had to come....), the latest bug on screen sharing forced me to look (for the 1000th time...) into the official client and see they had **FINALLY**(tm) fixed the SAML login bug, that I could access my account and that this was more or less functional, at least enough to do my job.

I might come back since I am not totally convinced the official client is totally stable. Thanks again a million and all the best for the future.

An impressed and delighted user

**Comment by IsmaelMartinez** [comment]
It's been a pleasure been useful. I am glad MS are starting to solve those problems, only taking them more than a year (and 10's of developers).

I will keep trying to keep fixing the issues that appear, the screensharing is now fixed in a branch, but I did almost give up on this one. 

Au revoir et bonne journée!
