### ISSUE TITLE
Screen sharing doesn't work

### ISSUE THREAD

**Issue by Glamhoth** [IsmaelMartinez/teams-for-linux#445]
**Describe the bug**
When clicking the button, I can see 'screen sharing' panel, but then choosing 'Desktop' doesn't open the window with the displays to share. It's working when running Teams on web, for example in Chrome. This but is present for at least 6 months.

**To Reproduce**
1. Join a call
2. Press screen sharing button
3. Choose 'Desktop/Window'

**Expected behavior**
Window with displays shows up.

**Desktop (please complete the following information):**
 - OS: Arch Linux (kernel 5.12.14)
 - Installation package: both via AUR and Flatpak

**Comment by jijojosephk** [comment]
This is fixed in 1.0.8 version. Could you verify? If you're facing issue since 6 months, you probably don't have the latest version. Fixed at #432. I'm not familiar with Arch. But flatpak may not be the latest one. I'm not sure about that only @IsmaelMartinez  can confirm. For Arch packages @frealgagu, could you help?

**Comment by Glamhoth** [comment]
I'll verify this then. It seems that AUR package is 1.0.8 now, so it should help

**Comment by Glamhoth** [comment]
And this indeed helped! 1.0.8 package is just three days old, that's why I missed it. Thanks for the help!

**Comment by jijojosephk** [comment]
@Glamhoth Glad that it works!
