### ISSUE TITLE
Consider to create Windows Builds

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#46]
Hi Ismael, I tried to find you outside Github (Twitter, or others) but coldn't make it.

Right now official Microsoft Teams client is not able to work with multiple accounts. Do you think that it's possible to generate the build for Windows? Just to give users an option to have 2 clients with different accounts.
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17750851-i-want-to-use-multiple-teams-accounts-at-the-same

(Maybe this will require a change of name of the app, to teams-desktop-client ... or not, it's your call)

**Comment by IsmaelMartinez** [comment]
Hi @julian-alarcon , 

I have no idea if that will work fully... it should work, because electron, but I can't really test it currently.

Maybe try with the https://www.electron.build/configuration/win (change the package.json and do as you did similar to snap)

It if works, that could be an experimental way... if people start using it then I can move/change the name of the project but are a few consequences to that.
