### ISSUE TITLE
Re-Login during active call

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#465]
**Describe the bug**
Using the client version 1.0.12 (and prior versions) sometimes it happens that Teams logs me out even if I am currently active in a call and asks for a relogin. This is really annoying. Anyway I can also imagine that this is the default behavior made by MS. So the question is, if this is solely happening in this unofficial client or if others encountered this also in the official MS client as I did once, if I remember correctly

**To Reproduce**
Can't explain how to reproduce. This seems to depend on the life time of the login session.

**Expected behavior**
Logging out should be postponed to a time when no call is active.

**Desktop (please complete the following information):**
 - Linux, openSuSE Leap 15.3, KDE
 - snap version 
 - Version 1.0.12

**Comment by jijojosephk** [comment]
@elhennig, This depends solely on how the security is defined in the organisation. Some would allow to "Keep signed in". Also there is a timeout within which the client should communicate to the server. All of these settings are controlled by office 365 and managed by the IT Team or other responsible teams. You would see this behaviour when you quit the app while logged in and open again so it would reload the page  skipping authentication but later at a random point it will push you out. Since teams-for-linux is a wrapper around the website provided by the Microsoft, it's difficult to fix on top of it organisational restrictions would take place and it becomes almost impossible to fix.

**Comment by elhennig** [comment]
Thanks for the explanation. This also might help to solve the problem, as the client then can be excluded from the list of possible causes ;-)

**Comment by jijojosephk** [comment]
@elhennig Thanks for reporting. Though each contributors are busy, there's a multi tenant feature under development. Though it's progressing slowly, it would come out one day.

**Comment by jijojosephk** [comment]
@elhennig Can I close this? :smile:  ?

**Comment by elhennig** [comment]
Yes, I guess so, I will ask our IT guys to solve this if this is a more global issue than I thought before.

**Comment by jijojosephk** [comment]
@elhennig You can try creating a new MS account and see if it's having the same issue. Teams is free I guess for any user now. But not sure.
