### ISSUE TITLE
Black window on wayland

### ISSUE THREAD

**Issue by hevanaa** [IsmaelMartinez/teams-for-linux#519]
Fedora 35 (Nvidia driver 510.47)
Installed from flatpak, version 1.0.23
When launched in Gnome Wayland session, only a black window is visible.
Application works normally in Gnome Xorg.
Application works in Wayland when started from command line with "--no-sandbox" argument.

**Comment by kon14** [comment]
You'll want to run Electron using the native Wayland backend.
Doesn't seem to work on 1.0.23's Electron build for Nvidia yet, but I custom built the Flatpak for _1.0.24-pre-release_ and it's working just fine with 510.47.03, including screensharing using Chromium's PipeWire WebRTC capturer.

As soon as the version is officially released and Flathub updates to it you should be able to get this working using `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer`.

You could test this on a terminal and confirm it's working, then make it so that it automatically launches like this like so:
`echo -e "--enable-features=UseOzonePlatform\n--ozone-platform=wayland\n--enable-features=WebRTCPipeWireCapturer" >> ~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/chromium-flags.conf`

Let me know if you wish to test this out sooner and need help building the Flatpak.

**Comment by IsmaelMartinez** [comment]
sorry, been away for a while for holidays and other commitments. I will try
to release that version soon. Apologies for the delay.

**Comment by IsmaelMartinez** [comment]
released now. Can you check if that works for you? Ta

**Comment by hevanaa** [comment]
Thanks, could you build the 1.0.24 flatpak? Or I'll do it at some point and check it.

**Comment by hevanaa** [comment]
Thanks, it is working now.
