### ISSUE TITLE
Incoming call notifications are appearing inside the app, instead of on the desktop

### ISSUE THREAD

**Issue by cs96and** [IsmaelMartinez/teams-for-linux#643]
**Describe the bug**
When someone calls me, the notification (with the phone, webcam & hangup buttons) is appearing inside the teams app, instead of on the dekstop above all other windows.  As the ringing sound comes through my headset (which I may not be wearing) I am sometimes unaware that someone is actually calling me if the teams window is minimized or below other windows.

**To Reproduce**
1. Get someone to call you on teams
2. Observe that the incoming notification is inside the teams window.

**Expected behavior**
The incoming call notification should be on the desktop, above all other windows.

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Installation package: deb
 - Version: 1.0.45

**Comment by jr-dimedis** [comment]
I can confirm that with Ubuntu 20.04.5, X11, Xfce, teams-for-linux deb v1.0.46.

As I am working with a bunch of virtual desktops I would expect that the incoming call dialog appears on the currently active virtual desktop.

Notifications about channel posts etc. are working fine and the same way as with the official app.

If you can give any hint of a starting point for that issue I would be glad to give it a try to fix this
by myself.

**Comment by IsmaelMartinez** [comment]
HI @cs96and and @jr-dimedis ,

We used to use the "notification hack" (using the config option `enableDesktopNotificationsHack`) described in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config#readme . Not even sure if it works anymore but worth checking if those notifications do show were you want them to see them.

I suspect is just because is electron (that is just basically a reduced browser) so without any work notifications will just stay in within the electron app/window.

If that works as you will expect, then maybe we can try to disable the other notifications when that "notification hack" is enabled.

Hope helps!

**Comment by cs96and** [comment]
> I suspect is just because is electron (that is just basically a reduced browser) so without any work notifications will just stay in within the electron app/window.

I'm sure this was working previously though.  I wonder if Microsoft have changed something recently, due to this...
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-progressive-web-app-now-available-on-linux/ba-p/3669846

**Comment by IsmaelMartinez** [comment]
That smells like a probable culpit, yes.

**Comment by cs96and** [comment]
Microsoft commented in the comment chain in that article...
> In progress: Fixing System notifications for Incoming Calls and Meeting Starts so you will see that you have an incoming call or a meeting has started even when you don't have the Teams PWA in the foreground.

**Comment by jr-dimedis** [comment]
Thanks for sharing this. So it looks we just have to wait until Microsoft fixes this in the PWA.

**Comment by opalmay** [comment]
Microsoft releasing broken software with basic features missing never ceases to amaze me..

**Comment by jijojosephk** [comment]
As far as I know draw something outside the window borders is impossible using electron. We can do though by creating a new browser window, but may be for that feature, the app has to use extra RAM. Because these notification come frequently and we can destroy and re-create the window every time. It's more like hide and show. Hiding does not release memory, may be that everyone understands and don't want to lecture :smile:

**Comment by cs96and** [comment]
I'm sure it used to draw the incoming call notification outside the window
in the past though.  This has only changed in the last few weeks.

**Comment by jijojosephk** [comment]
@cs96and I don't think that would happen because the web version of the app cannot show pop out windows. Must be there with the official app.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
