### ISSUE TITLE
teams does not store login credentials

### ISSUE THREAD

**Issue by zhao-nan** [IsmaelMartinez/teams-for-linux#648]
When starting teams-for-linux (on Ubuntu 20.04), after providing my login data, a dialog asks me whether to stay signed in, and whether to ask again. Whatever options I choose, the same dialog appears on the next startup, and I need to sign in again. This is annoying because I log on every day and would actually like to stay signed in.
All my colleagues using Teams on Linux have the same issue.

I had still problem already when using the official client for Linux, but their support could not help me. Since the problem persists also with this unofficial client, I thought I'd ask here as well.

**Comment by IsmaelMartinez** [comment]
Hi @zhao-nan , have you tried using the "deb" version? I wonder if your snap configuration is not allowing whatever MS uses to persist the cookies/password. 

Otherwise, do you have the same problem with opening it on the browser? Or does it persist the session when you close the browser and open it again? Hope helps

**Comment by IsmaelMartinez** [comment]
I suspect then your company policies might be the issue. Check with your network admin. Also, if it also happens on the browser, we will not be able to help from here. Sorry about that. ("We" is normally only me and @jijojosephk this days)

**Comment by zhao-nan** [comment]
No need to apologize! I already suspected that my issue is not really something for you to fix. Thank you for indulging me, and for your work with this client.
