### ISSUE TITLE
Back/forward navigation buttons

### ISSUE THREAD

**Issue by bmaupin** [IsmaelMartinez/teams-for-linux#681]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Hi,

The official Teams app for Linux has back/forward buttons that are very useful navigating back and forth quickly between chats. Would it be possible to add them?

Thanks!

**Describe alternatives you've considered**

For the time being, I'm able to use the back/forward navigation buttons on my mouse, but I don't have those with every mouse I use.

**Additional context**

This is what they look like in the official Teams Linux app (I don't really care what they look like, just thought a screenshot would be helpful):

![teams-navigation-buttons](https://user-images.githubusercontent.com/346123/220420052-3eeba71f-55d2-450e-a4ea-2a7b25eabf4f.png)

**Comment by IsmaelMartinez** [comment]
Hi @bmaupin,

Thanks for pinging. That feature will require having window on the top of the browser window... aka, it is a bit bigger than what you might think.

I will suggest asking in the MS uservoice (or whatever is called now) for that support to be added to the browser version. They got tones of developers (even if unfortunately they have fired thousands lately) so they should be able to do it faster than in here.

But if you feel brave enough, let me know and I can see if I can give you any pointers on how this might be done. Currently I have no idea, but because I haven't look at it (got no time unfortunately)

**Comment by IsmaelMartinez** [comment]
by the way, seems like you aren't the only one with that wish https://github.com/IsmaelMartinez/teams-for-linux/issues/678

**Comment by bmaupin** [comment]
> Thanks for pinging. That feature will require having window on the top of the browser window... aka, it is a bit bigger than what you might think.

Is that necessary? I'm not actually asking for #678, just the back/forward navigation buttons. The native title bar doesn't bother me. It doesn't matter to me where the navigation buttons are.

**Comment by IsmaelMartinez** [comment]
Unfortunately it is. currently we only have a browserwindow that opens the page in the electron "browser". But I am all ears if you know or think of other options to add those back/forward buttons. Maybe try the keyboard shortcuts (not sure if the back/forward options are there)

**Comment by jijojosephk** [comment]
@bmaupin there's a pre-release `1.0.74`. You can use 'ALT' + 'LEFT' for previous and 'ALT' + 'RIGHT' next. Having buttons for these looks very difficult.

**Comment by jijojosephk** [comment]
@bmaupin please report if this helps. You can use keyboard short cuts to achieve the same.
