### ISSUE TITLE
Add prompt for camera for snap installations (1st use) 

### ISSUE THREAD

**Issue by benyanke** [IsmaelMartinez/teams-for-linux#69]
The docs say you need to run `sudo snap connect teams:camera core:camera` to enable the camera.

I suggest adding a popup on the first time if that permission isn't granted (remmina does this for a similar permission) so that the user knows.

**Comment by IsmaelMartinez** [comment]
That will imply:
* Detecting the system is running snap (or failing to use the camera because no permissions)
* Creating a dialog asking for permission.
* Running the command in the node part of electron.

From all of those options... the last one might be the most difficult. 

A compromise might be a:
* if detecting the camera is not working, show the command in a pop-up (dialog) with whatever the information the user needs (link to snap containment etc)

**Comment by benyanke** [comment]
I don't think the third line item is actually possible - it would kind of defeat the point of the secure snap container!

What I'm proposing is a simple popup saying "If you want to use your camera, please paste 'sudo snap connect teams:camera core:camera' into your terminal'". This is what remmina does, and is - from what I can find - the best practice for this subpar workflow.

**Comment by IsmaelMartinez** [comment]
The idea will be to detect is a "snap" app. Otherwise we are spamming people with something they don't need todo.

If is not possible to detect is a snap app in running time, it should be possible to build it with a flag (or something), to show the message in 1st build. We are running bash in a container so adding a "flag file" or similar to the snap app will not be difficult.

**Comment by IsmaelMartinez** [comment]
If you @benyanke and @julian-alarcon are happy with the "flag" option, then this should probably be the second part of #74 . I put it in 0.1.18 project and see if we can release it as in that version.

Assigning to you two as you are the snap gurus ;)

**Comment by julian-alarcon** [comment]
I just check how Remmina defines to show or not this message.

https://github.com/FreeRDP/Remmina/pull/1545/commits

They try to use an specific service (secret), if Remmina is not able to use that then the prompt is show.

We will have to do develop a similar approach on teams-for-linux for the camera and then show the message (this may cause to show the warning on a different build besides snap if not camera is found)

**Comment by IsmaelMartinez** [comment]
Related to #128 . We need to be able to identify the system

**Comment by IsmaelMartinez** [comment]
Closing as to be able to identify the system will require quite a bit of work. Also, noone have shown interest in implementing it.
