### ISSUE TITLE
mass reloading, can't sign out of the app to fix the issue

### ISSUE THREAD

**Issue by t3dium** [IsmaelMartinez/teams-for-linux#693]
likely mass reloading as i changed my email for my microsoft account, i can't press the sign out button since it auto refreshes extremely fast. I also tried uninstalling the flatpak with the --delete-data flag, and it doesn't look like its logged me out? it still mass refreshes to the below page, not allowing me to signout or use the app:

![image](https://user-images.githubusercontent.com/83690012/222566016-17bc4a48-bcde-4f17-9a12-73c1ed5d8f94.png)

A log out option on the tray icon, which clears cookies, would likely fix this issue

**Comment by IsmaelMartinez** [comment]
hi, 

Can you maybe try:  `teams-for-linux --clearStorage` ?

That should clear your local config and cache... I think it then fails but the next start should be hopefully ok. 

Otherwise check if you can clear the folder of it. More info in here:

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md

**Comment by t3dium** [comment]
The command failed, “teams-for-linux” not found. I’ve installed it as a flatpak. I tried deleting the entire data directory, which did successfully log me out, and I signed in. But when I open a teams link in my browser, it says “signing you out of all accounts” and proceeds to sign out. And repeats this every time.

**Comment by jijojosephk** [comment]
Try this:

`flatpak run com.github.IsmaelMartinez.teams_for_linux --clearStorage`

**Comment by t3dium** [comment]
issue seems to have gone away now, apps working
