### ISSUE TITLE
Wayland Screen sharing doesn't work. Also no `Devices` tab in settings to check how your devices works.

### ISSUE THREAD

**Issue by bigkrp** [IsmaelMartinez/teams-for-linux#733]
**Describe the bug**
On call I want to share my screen.

**To Reproduce**
1. Click Share button
2. Click `Screen, window or tab` button
3. Select `Entire Screen` 
4. Nothing share

**Expected behavior**
My screen is sharing on call.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 37
 - Installation package: flatpack
 - 1.0.24

**Comment by pablaasmo** [comment]
Works when using AppImage distribution.
OS: Linux Fedora Workstation 37
Installation package: AppImage
1.0.60

**Comment by astroman68** [comment]
Works for me on Manjaro base w/ Hyprland. Your devices can be accessed just before you join the call and during call. Keep in mind, this is not the native Windows desktop release. It is 'based' around the web-based version run in electron. This link may give you some insight on what you need to make screen sharing work native in your environment. Hope it helps.

[https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Screen-Sharing/](url)

**Comment by rkozlo** [comment]
>     * Installation package: flatpack
> 
>     * 1.0.24

A bit old. Try with newer. I have no problem with wayland + kde

**Comment by bigkrp** [comment]
I've downloaded latest v1.0.60  `*.rmp`  and screen sharing works in that case, that people on call can see it, but I can't see that I'm sharing something, for instance no any red border on the screen.

**Comment by rkozlo** [comment]
I don't have red border either. For me it isn't big problem. I'm glad it is working. But if you change title developer will look at this and try to fix

**Comment by jijojosephk** [comment]
@bigkrp and @rkozlo, drawing the border may not be possible, because we're playing within the limits of chromium engine and electron. We may be able to achieve something with creating a new browser window having the body transparent with possibly red borders, I'm not sure.  But it's going to instantiate a browser window object and it's going increase the memory usage. Do you think any other visual cues could possibly help the user understand the screen is being shared? If the user on headphone, an audio note at fixed interval would help. May be a 'beep' :laughing:

**Comment by jijojosephk** [comment]
I guess the screen sharing is working hence closing the issue. Please re-open if you think something is broken.

**Comment by bigkrp** [comment]
@jijojosephk In some prev version of "official" client they just showed the screen, that was sharing on call.
