### ISSUE TITLE
Large Gallery View

### ISSUE THREAD

**Issue by MrHappy** [IsmaelMartinez/teams-for-linux#755]
The 'Large Gallery View' is in the list, but always greyed out.
Or this is because of configuration on my end?

Is it possible to have this option selectable/available?

**Comment by RolandRosenfeld** [comment]
As far as I can see, this is some "bug" in the microsoft PWA: The large gallery view seems to be only available if at least 9 people are are online, so you can see <=4 people with the default view or >9 people in the large gallery, but only 4 between 4 and 9 participants.
To make the behavior more random: it feels that the >9 people have to enter the conference before you, otherwise the large gallery isn't available often.  But if somebody leave the conference, the large gallery stays available.

Since all this isn't really usable or predictable, I currently use either an iPAD as a second screen with the large gallery or the "Zusammen-Modus" (placing all participants like in a cinema or lecture hall, don't know how this is named in English).  After using it multiple times now, it's more usable than expected and with better video quality than the large gallery, which sometimes has very ugly artifacts and delay.

Having said this, I don't have any idea if there is a chance for teams-for-linux to fix the large gallery, if it is disable by the PWA.

**Comment by jijojosephk** [comment]
May not be worth working on this one as the MS version is having the problem. Sorry about this. If you think about any JavaScript hack, kindly re-open and suggest what can be done or open an PR.
