### ISSUE TITLE
Hovering on Links Shows A Different Type of Cursor Than System Default

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#96]
**Is your feature request related to a problem? Please describe.**
Cursor does not look good on the hyperlinks.

**Describe the solution you'd like**
Provide the system default cursor for the links.

**Describe alternatives you've considered**
Nil. I really appreciate you for bringing teams to Linux. Great effort!

**Additional context**
Tested on 0.1.18 Edge.
[MSTeamsLinuxDifferentCursor.zip](https://github.com/IsmaelMartinez/teams-for-linux/files/3053340/MSTeamsLinuxDifferentCursor.zip)

**Comment by IsmaelMartinez** [comment]
This is dependent on your cursor theme. It does uses the same cursor as in the browser.

Can you confirm you are seen the same in the browser as in the app? I will close this as, if that is not the case, this should be a bug.

**Comment by jijojosephk** [comment]
In the browser it's working fine. Attached video in the zip file.
Browser : Google Chrome
Version  : 73.0.3683.103 (Official Build) (64-bit)
[BehaviourInBrowser.zip](https://github.com/IsmaelMartinez/teams-for-linux/files/3056940/BehaviourInBrowser.zip)

**Comment by jijojosephk** [comment]
@IsmaelMartinez Isn't it an issue? I tested in Chromium as well.

**Comment by IsmaelMartinez** [comment]
Report it as a bug with as much info as you can provide (including the stuff you did put in here). the "not an issue" is because this is not a new feature (as you report it). I will remove that tag. Can you also try with the deb package just to check if that is a snap only related issue? And try with version 0.1.17 (both snap and not deb).

Thanks and apologies for the confusing tag

**Comment by jijojosephk** [comment]
@IsmaelMartinez  Thank you. I'll report it as a bug.

**Comment by jijojosephk** [comment]
@IsmaelMartinez created a new bug #99
