### ISSUE TITLE
Screen share is black on Wayland

### ISSUE THREAD

**Issue by raekya** [IsmaelMartinez/teams-for-linux#961]
**Describe the bug**
When sharing my screen or a window, the other person only sees black.
**To Reproduce**
1. Get in a call or meeting
2. Share screen/window

**Expected behavior**
The other person sees what I see.
**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux (NixOS)
 - Installation package: nixpkgs-unstable
 - Version 1.3.11 (also happens on 1.3.8)
 
**Additional context**
In 1.0.93 (nixpkgs 23.05), it used to work, but the other person would hear me twice if I didn't mute myself. I didn't file a separate bug report for this since I wanted to test this on a newer version. I am running KDE on Wayland.

**Comment by 1ndev-ui** [comment]
Can confirm, having the same issue.

**Comment by jijojosephk** [comment]
This is more distribution and package related problem. Frankly, I won't be able to look at this because I know nothing about nix package.

I believe someone uses nix in the chat room. I urge you to join the channel and shoot some questions.

https://matrix.to/#/#teams-for-linux_community:gitter.im

From the application's point of view we have a lot of limitations.

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. Hope you find the solution.

**Comment by muelli** [comment]
> This is more distribution and package related problem

what is the problem, then?

I'm experiencing the same with standard Ubuntu.

**Comment by muelli** [comment]
well, actually, I'm having it the other way around: *I* am seeing black for any shared screen. The others can see my screen well.

**Comment by IsmaelMartinez** [comment]
Hi, can you check with one of the more "classic" packaging systems (deb or rpm). Just to make sure this is not related to a package system permissions (like snap etc)

**Comment by romo467** [comment]
just checked with the 1.3.13 .deb in ubuntu 22.04 with ungoogled-chromium 117.0.5938.149-1~xtradeb1 and as the presenter I do not see the shared screen oder window.

**Comment by lowgos** [comment]
Hi everyone, I'm on NixOS myself and I just had to try this app because Microsoft is making it harder and harder to use the original one.
While updating my NixOS flake I had an error message about this deprecation preventing me to go further. I could have silenced it in someway to continue but I wanted to find an alternative.

This project works fine on my end, I'm guessing most NixOS + Teams users will migrate here in the future because PWA on NixOS is a bit of a hassle.

I just tested and calls, screen sharing and everything else seems to work out of the box. I didn't have to configure anything yet. I may have something else in my NixOS configuration that is the "culprit" for making it work compared to yours @raekya but I cannot share my config yet.

FYI I'm on Gnome + Wayland on the unstable branch of nixpkgs and everything has just gotten updated.

**Comment by demsey** [comment]
> Hi, can you check with one of the more "classic" packaging systems (deb or rpm). Just to make sure this is not related to a package system permissions (like snap etc)

When I share the screen in the snap version, I get a message like "You don't have permission to use the camera".
**However, in classic deb version 1.3.19, screen sharing works great**

**Comment by Vagrantin** [comment]
I'm wondering if this issue and this issue #999 could have the same cause, Wayland ... ?
My2cents.

**Comment by Hydranet** [comment]
I just wanted to share about half a year back or so I had this issue, but I tried again today and I am able to sharing my screen when logged into a Wayland session on Gnome.

**Comment by sladiri** [comment]
> well, actually, I'm having it the other way around: _I_ am seeing black for any shared screen. The others can see my screen well.

I've had this problem as well since about one or two weeks. I am on Fedora 39, using Edge Beta which has worked before quite well for over a year.

**Comment by Gorship** [comment]
I also am having issues with Teams-For-Linux and this seems like the most appropriate thread to add to

I posted this on the nix discourse -- slightly adjusted for here

Using teams for work and currently if I attempt to screen-share: 
- Its a cropped 
- lower resolution version of the monitor I am sharing. 

Also there’s no preview, or way to see which monitor is being shared (however this appears to be something that’s gnome related and being worked on ? - [This thread perhaps indicates its a gnome thing?](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/9)

**Work around:**
Dropping into gnome x11 completely resolves this and works like a charm - bit of screen tearing on my vertical mon that i use for reading articles / music but not awful.

**Potential wayland workarounds attempted:**

**Using Chrome on Wayland:**
Does not resolve this completely, I get a different set of issues. The refresh rate isnt quite up to par doing it this way and if I’m clicking around or demonstrating something – the viewer gets confused whats happening.

small spec sheet:
nix 23.11.1779
Kernel 6.1.67
gnome 56.2

Apps tried
Teams-for-linux nix pkg
> I should note that the depreciated 1.0.93 prior to updating to Nix 23.11 was working
Teams-for-linux flatpak
" appimage

have not tried the appimage just released a couple days ago 

**Closing notes:**
Due to the issues in the app, and (while slightly better but still buggy) chrome I dont know if this is simply something I can kick into the "wayland bugs" bucket and let it cook for a while or what. If it is fixable and something to look at then great.

However, if other wayland users on different distros are doing great with the current Teams-For-Linux flatpak, appimage etc then I can maybe see if the maintainers have noticed anything.

Apologies if this is the wrong spot or something - like that. Long time lurker, not much of a commenter :). 
Best,

**Comment by IsmaelMartinez** [comment]
Closing this issue to clean the open issues. This is because there hasn't been activity for a few months now. If you still face this issue in versions 1.4.1 and above, please share it and we can re-open it. Thanks in advance!
